Repository digital-peaks/web-aoa, pull requests merged in 2021-11, with the labels that each got.

#2 setup basic structure and CI/CD
  .dockerignore
  .env.example
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .gitignore
  Dockerfile
  README.md
  docker-compose.yaml
  mongo/init-mongo.js
  package-lock.json
  package.json
  src/app.js
  src/index.js
  src/utils/logger.js
Labels: enhancement

#10 fix EOL for windows
  .gitignore
  package.json
Labels: bug

#11 add basic job routes
  mongo/init-mongo.js
  package-lock.json
  package.json
  src/app.js
  src/job/job.model.js
  src/job/job.routes.js
  src/job/job.service.js
  src/routes.js
  src/utils/exceptions/BadRequestException.js
  src/utils/exceptions/BaseException.js
  src/utils/exceptions/InternalServerErrorException.js
  src/utils/exceptions/NotFoundException.js
  src/utils/exceptions/UnauthorizedException.js
  src/utils/exceptions/index.js
  src/utils/exceptions/requestErrorHandler.js
  src/utils/mongoose/index.js
  src/utils/mongoose/paginate.plugin.js
  src/utils/mongoose/toJSON.plugin.js
Labels: enhancement, api
