Repository digital-peaks/web-aoa, pull requests merged in 2022-01, with the labels that each got.

#72 R dynamic resolution
  r/aoa_script.R
  r/test/classification_image.tif.aux.xml
  r/test/job_param.json
  r/test/model.rds
Labels: enhancement, r-script

#73 R additional mla
  r/aoa_script.R
  r/test/job_param_svm.json
Labels: enhancement, r-script

#75 R result json
  r/aoa_script.R
  r/test/pred_1.tif.aux.xml
  r/test/result.json
Labels: r-script

#76 add user routes
  .env.example
  docker-compose.yaml
  package-lock.json
  package.json
  src/app.js
  src/auth/api-key.middleware.js
  src/auth/auth.middleware.js
  src/auth/passport.js
  src/docs/components.yaml
  src/routes.js
  src/user/user.model.js
  src/user/user.routes.js
  src/user/user.service.js
  src/user/utils/generateFingerprint.js
  src/user/utils/index.js
Labels: enhancement, api

#82 enhance docker-compose for production use
  .env
  .env.example
  .gitignore
  Makefile
  README.md
  docker-compose.yaml
  migration/create-user.js
  mongo/init-mongo.js
  mongo/init-mongo.sh
  src/job/job.service.js
Labels: documentation, enhancement

#84 add env API_URL
  .env
  Makefile
  README.md
  docker-compose.yaml
  src/docs/swaggerDef.js
  src/job/job.service.js
Labels: documentation, api

#85 use Haproxy
  .env
  README.md
  docker-compose.yaml
  migration/create-user.js
  ops/haproxy/haproxy.cfg
  ops/haproxy/haproxy.local.cfg
  ops/haproxy/haproxy.production.cfg
  src/routes.js
Labels: documentation

#89 add machine learning hyperparameters
  r/aoa_script.R
  r/test/job_param.json
  r/test/job_param_svm.json
  src/docs/components.yaml
  src/job/job.model.js
  src/job/job.routes.js
  src/job/utils/convertForR.js
Labels: documentation, enhancement, api

#91 fix machine learning params for R script
  src/job/job.service.js
  src/job/utils/convertForR.js
Labels: bug, api

#92 R testing
  Dockerfile
  r/aoa_script.R
  r/test/aoi.gpkg
  r/test/classification_image.tif.aux.xml
  r/test/job_param.json
  r/test/job_param_svm.json
  r/test/model.rds
  r/test/pred_1.tif.aux.xml
  r/test/result.json
  r/test/samplePolygons.gpkg
  r/test/samples.gpkg
  r/test/samples2.geojson
  r/test/samples_Meyer_4326.geojson
Labels: r-script

#107 upgrade HAProxy to 2.5
  docker-compose.yaml
Labels: enhancement

#108 fix machine learning error when using a model
  src/job/job.service.js
Labels: bug, api

#110 add tests for job and user services
  .github/workflows/test.yml
  .gitignore
  package.json
  src/job/job.service.js
  src/job/job.service.spec.js
  src/user/user.service.spec.js
Labels: api, qa

#114 add R protocol timestamp
  src/job/job.service.js
Labels: enhancement, api
